import random
import numpy as np

""" PARAMETERS  """
# Random seed
random.seed(10)
np.random.seed(10)


# MAP PARAMETERS
COST_MAP_PATH = "Cost_map.txt"
PRODUCTION_MAP_PATH = "Production_map.txt"
USAGE_MAP_PATH = "Usage_map.txt"
MAP_COST_RATIO = 10000
BUDGET = 500000

# ALGORITHM PARAMETERS
""" GENETIC PARAMETERS """
POPULATION_SIZE = 200
NB_ITERATION = 300

SEUIL_DIFF_COMPACITE = 0.015
SEUIL_DIFF_PROXIMITE = 0.015
SEUIL_DIFF_PRODUCTION = 0.015

""" PROMETHEE PARAMETERS """
WEIGHTS = [.34, .33, .33]
INDIFFERENCE_THRESHOLD_EMPLACEMENT = 0.4
PREFERENCE_THRESHOLD_EMPLACEMENT = 0.6

# TEST MAP PARAMETERS
TEST_MAP_PATH = "20x20_"
TEST_MAP_DIMENSION = (20, 20)

# CONFIGURATION
USING_TEST_MAP = False
USING_DATA_PLOT = True
USE_EVOLUTION_LOOP = True
PLOTTING_BLUE_POINTS = False




