""" PARAMETERS  """

# MAP PARAMETERS
COST_MAP_PATH = "Cost_map.txt"
PRODUCTION_MAP_PATH = "Production_map.txt"
USAGE_MAP_PATH = "Usage_map.txt"
MAP_COST_RATIO = 10000
BUDGET = 500000

# ALGORITHM PARAMETERS
""" GENETIC PARAMETERS """

""" PROMETHEE PARAMETERS """
WEIGHTS = [.34, .33, .33]
INDIFFERENCE_THRESHOLD_EMPLACEMENT = 0.4
PREFERENCE_THRESHOLD_EMPLACEMENT = 0.6

# TEST MAP PARAMETERS
TEST_MAP_PATH = "20x20_"
TEST_MAP_DIMENSION = (20, 20)

# CONFIGURATION
USING_TEST_MAP = False
USING_DATA_PLOT = False
USE_EVOLUTION_LOOP = True